# Generated by Django 2.1.8 on 2019-08-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion_post',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='promotion_post',
            name='image',
        ),
    ]
