# Generated by Django 2.1.7 on 2019-08-08 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_review1_post_image_review2_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review1_post',
            name='major',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review1_post',
            name='major_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review1_post',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review1_post',
            name='university',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review2_post',
            name='major',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review2_post',
            name='major_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review2_post',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review2_post',
            name='university',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review1_post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review1_post',
            name='heart_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='review1_post',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=1000, null=True, verbose_name='imageurl'),
        ),
        migrations.AlterField(
            model_name='review1_post',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='review1_post',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review1_post',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review1_post_comment',
            name='commented_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='review1_post_comment',
            name='commented_post',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review1_post_comment',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review1_post_comment',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review1_post_image',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=1000, null=True, verbose_name='imageurl'),
        ),
        migrations.AlterField(
            model_name='review1_post_image',
            name='imaged_post',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review2_post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review2_post',
            name='heart_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='review2_post',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=1000, null=True, verbose_name='imageurl'),
        ),
        migrations.AlterField(
            model_name='review2_post',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='review2_post',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review2_post',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review2_post_comment',
            name='commented_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='review2_post_comment',
            name='commented_post',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review2_post_comment',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review2_post_comment',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='review2_post_image',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=1000, null=True, verbose_name='imageurl'),
        ),
        migrations.AlterField(
            model_name='review2_post_image',
            name='imaged_post',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
