# Generated by Django 2.2.1 on 2019-08-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190806_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion_post',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
