# Generated by Django 2.2.1 on 2019-08-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_promotion_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion_comment',
            name='post_id',
            field=models.IntegerField(null=True),
        ),
    ]
