# Generated by Django 2.2.3 on 2019-08-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190807_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_post',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
