# Generated by Django 2.2.3 on 2019-08-06 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190807_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_post',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='notice_post',
            name='title',
            field=models.CharField(default='none', max_length=500),
        ),
    ]
